# Generated by Django 4.0.6 on 2022-07-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResponce',
        ),
    ]
