# Generated by Django 4.0.6 on 2022-07-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quizresponces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresponces',
            old_name='user_emil',
            new_name='user_email',
        ),
    ]
