# Generated by Django 4.0.6 on 2022-07-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_user_emil_quizresponces_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponces',
            name='user_responce',
        ),
        migrations.AddField(
            model_name='quizresponces',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
