# Generated by Django 4.0.6 on 2022-07-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_quizresponces_user_responce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponces',
            name='attempt_quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_quiz', to='main.quizname'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresponces',
            unique_together={('user_email', 'user_question')},
        ),
    ]
