# Generated by Django 4.0.6 on 2022-07-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quizresponces_attempt_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='timer',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
